"""make_models: generate ORM model files from the live database schema.

Styles: peewee, sqlalchemy, connector. Generation is pure text — the target
ORM does not have to be installed to generate its models.
"""

from __future__ import annotations

import re
from pathlib import Path

from connector.errors import SchemaError
from connector.schema import ColumnDef, SchemaDef, TableDef, fk_order

_STYLES = ("peewee", "sqlalchemy", "connector")


def _class_name(table: str) -> str:
    return "".join(part.capitalize() for part in table.split("_")) or table.capitalize()


def _split_type(ctype: str) -> tuple[str, str | None, bool]:
    """'varchar(100)[]' -> ('varchar', '100', True)"""
    array = ctype.endswith("[]")
    if array:
        ctype = ctype[:-2]
    # enum/custom type names may contain digits and mixed case (status_v2)
    m = re.match(r"^([A-Za-z_][A-Za-z0-9_ ]*?)(?:\((.+)\))?$", ctype)
    if m is None:
        raise SchemaError(f"make_models(): cannot parse column type {ctype!r}")
    return m.group(1), m.group(2), array


# -- peewee ------------------------------------------------------------------------

_PEEWEE_TYPES = {
    "serial": "AutoField",
    "bigserial": "BigAutoField",
    "integer": "IntegerField",
    "bigint": "BigIntegerField",
    "smallint": "SmallIntegerField",
    "boolean": "BooleanField",
    "text": "TextField",
    "numeric": "DecimalField",
    "real": "FloatField",
    "double precision": "DoubleField",
    "date": "DateField",
    "timestamp": "DateTimeField",
    "timestamptz": "DateTimeField",
    "time": "TimeField",
    "uuid": "UUIDField",
    "bytea": "BlobField",
    "json": "TextField",
    "jsonb": "TextField",
}


def _peewee_field(col: ColumnDef, enums: dict, class_names: dict[str, str]) -> str:
    base, mods, array = _split_type(col.type)
    args: list[str] = []
    comment = f"  # {col.comment}" if col.comment else ""

    if col.references:
        target = class_names.get(col.references[0], _class_name(col.references[0]))
        args = [target, f'column_name="{col.name}"', f'field="{col.references[1]}"',
                f'backref="{col.name}_set"']
        if not col.not_null:
            args.append("null=True")
        return f'    {col.name} = ForeignKeyField({", ".join(args)}){comment}'

    if base in enums:
        field = "CharField"
        comment = f"  # enum {base}: {', '.join(enums[base])}" + (
            f" | {col.comment}" if col.comment else ""
        )
    elif base == "varchar":
        field = "CharField"
        if mods:
            args.append(f"max_length={mods}")
    elif base == "char":
        field = "FixedCharField"
        if mods:
            args.append(f"max_length={mods}")
    elif base == "vector":
        field = "TextField"
        comment = f"  # pgvector vector({mods})" + (f" | {col.comment}" if col.comment else "")
    elif base == "numeric" and mods:
        field = "DecimalField"
        digits = [x.strip() for x in mods.split(",")]
        args.append(f"max_digits={digits[0]}")
        if len(digits) > 1:
            args.append(f"decimal_places={digits[1]}")
    else:
        field = _PEEWEE_TYPES.get(base, "TextField")

    if array:
        comment = "  # postgres array — use playhouse.postgres_ext.ArrayField" + (
            f" | {col.comment}" if col.comment else ""
        )
        field = "TextField"
    if col.primary and field not in ("AutoField", "BigAutoField"):
        args.append("primary_key=True")
    if col.unique and not col.primary:
        args.append("unique=True")
    if not col.not_null and not col.primary and field not in ("AutoField", "BigAutoField"):
        args.append("null=True")
    return f'    {col.name} = {field}({", ".join(args)}){comment}'


def render_peewee(schema: SchemaDef, database: str) -> str:
    class_names = {t.name: _class_name(t.name) for t in schema.tables}
    lines = [
        '"""Peewee models generated by connector.make_models — do not edit by hand."""',
        "",
        "from peewee import (",
        "    AutoField, BigAutoField, BigIntegerField, BlobField, BooleanField,",
        "    CharField, DateField, DateTimeField, DecimalField, DoubleField,",
        "    FixedCharField, FloatField, ForeignKeyField, IntegerField, Model,",
        "    PostgresqlDatabase, SmallIntegerField, TextField, TimeField, UUIDField,",
        ")",
        "",
        f'database = PostgresqlDatabase("{database}")  # configure host/user/password',
        "",
        "",
        "class BaseModel(Model):",
        "    class Meta:",
        "        database = database",
        "",
    ]
    # FK order: referenced model classes must exist before the referencing ones
    for table in fk_order(schema.tables):
        lines.append("")
        lines.append(f"class {class_names[table.name]}(BaseModel):")
        for col in table.columns:
            lines.append(_peewee_field(col, schema.enums, class_names))
        lines.append("")
        lines.append("    class Meta:")
        lines.append(f'        table_name = "{table.name}"')
        lines.append("")
    return "\n".join(lines)


# -- sqlalchemy -----------------------------------------------------------------------

_SA_TYPES = {
    "serial": "Integer",
    "bigserial": "BigInteger",
    "integer": "Integer",
    "bigint": "BigInteger",
    "smallint": "SmallInteger",
    "boolean": "Boolean",
    "text": "Text",
    "numeric": "Numeric",
    "real": "Float",
    "double precision": "Float",
    "date": "Date",
    "timestamp": "DateTime",
    "timestamptz": "DateTime(timezone=True)",
    "time": "Time",
    "uuid": "UUID(as_uuid=True)",
    "bytea": "LargeBinary",
    "json": "JSONB",
    "jsonb": "JSONB",
}


def _sa_type(col: ColumnDef, enums: dict) -> tuple[str, str]:
    base, mods, array = _split_type(col.type)
    note = ""
    if base in enums:
        sa = f'PGEnum({", ".join(repr(v) for v in enums[base])}, name="{base}")'
    elif base == "varchar" or base == "char":
        sa = f"String({mods})" if mods else "String"
    elif base == "numeric" and mods:
        sa = f"Numeric({mods})"
    elif base == "vector":
        sa = "Text"
        note = f"  # pgvector vector({mods}) — use pgvector.sqlalchemy.Vector"
    else:
        sa = _SA_TYPES.get(base, "Text")
    if array:
        sa = f"ARRAY({sa})"
    return sa, note


def _sa_column(col: ColumnDef, enums: dict) -> str:
    sa, note = _sa_type(col, enums)
    args = [sa]
    if col.references:
        args.append(f'ForeignKey("{col.references[0]}.{col.references[1]}")')
    if col.primary:
        args.append("primary_key=True")
    if col.unique and not col.primary:
        args.append("unique=True")
    if col.not_null and not col.primary:
        args.append("nullable=False")
    if col.comment:
        note = f"  # {col.comment}" + note
    return f'    {col.name} = Column({", ".join(args)}){note}'


def render_sqlalchemy(schema: SchemaDef, database: str) -> str:
    lines = [
        '"""SQLAlchemy models generated by connector.make_models — do not edit by hand."""',
        "",
        "from sqlalchemy import (",
        "    BigInteger, Boolean, Column, Date, DateTime, Float, ForeignKey, Integer,",
        "    LargeBinary, Numeric, SmallInteger, String, Text, Time,",
        ")",
        "from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID",
        "from sqlalchemy.dialects.postgresql import ENUM as PGEnum",
        "from sqlalchemy.orm import declarative_base",
        "",
        "Base = declarative_base()",
        f'# database: "{database}"',
        "",
    ]
    for table in schema.tables:
        lines.append("")
        lines.append(f"class {_class_name(table.name)}(Base):")
        lines.append(f'    __tablename__ = "{table.name}"')
        lines.append("")
        for col in table.columns:
            lines.append(_sa_column(col, schema.enums))
        lines.append("")
    return "\n".join(lines)


# -- connector ------------------------------------------------------------------------------

def render_connector(md_text: str) -> str:
    return "\n".join(
        [
            '"""Schema module generated by connector.make_models — do not edit by hand."""',
            "",
            "from connector import PostgreSQLConnector",
            "",
            'SCHEMA_MD = """\\',
            md_text.replace("\\", "\\\\").replace('"""', '\\"\\"\\"'),
            '"""',
            "",
            "",
            "def get_db(**kwargs) -> PostgreSQLConnector:",
            '    """Connect and make sure the schema exists (additive init)."""',
            "    db = PostgreSQLConnector(**kwargs)",
            "    db.init_db(md=SCHEMA_MD)",
            "    return db",
            "",
        ]
    )


# -- entry point ---------------------------------------------------------------------------------


def make_models(connector, path="models/", style="connector") -> list[Path]:
    styles = [style] if isinstance(style, str) else list(style)
    unknown = set(styles) - set(_STYLES)
    if unknown:
        raise SchemaError(f"Unknown model style(s) {sorted(unknown)}: expected {_STYLES}")

    from connector.schema import collapse_multilanguage, introspect_schema

    physical = introspect_schema(connector.manager, connector.config.langs)
    physical.tables = [  # models map real tables; views have no pg_class 'r' entry anyway
        TableDef(name=t.name, columns=t.columns) for t in physical.tables
    ]
    out_dir = Path(path)
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for s in styles:
        target = out_dir / f"{s}_models.py"
        if s == "peewee":
            text = render_peewee(physical, connector.config.database)
        elif s == "sqlalchemy":
            text = render_sqlalchemy(physical, connector.config.database)
        else:
            from connector.markdown import render_md

            logical = collapse_multilanguage(physical)
            text = render_connector(render_md(logical))
        target.write_text(text, encoding="utf-8")
        written.append(target)
    return written
